//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOUE
    {
        public int ID { get; set; }
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<int> ID_VEHICULE { get; set; }
        public int NB_KM { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual VEHICULE VEHICULE { get; set; }
    }
}
